name       : brisk-menu
version    : 0.4.5
release    : 8
source     :
    - https://github.com/solus-project/brisk-menu/releases/download/v0.4.5/brisk-menu-0.4.5.tar.xz : 2dbb6da64d5dd571de8e00db795e8ec58a08453055fd82c024743dd54ba3456e
license    :
    - GPL-2.0
    - CC-BY-SA-4.0
component  : desktop.mate
summary    : An efficient menu for the MATE Desktop
description: |
    An efficient menu for the MATE Desktop, from the Solus developers.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmate-menu)
    - pkgconfig(libmatepanelapplet-4.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
