name       : brisk-menu
version    : 0.5.0
release    : 12
source     :
    - git|https://github.com/solus-project/brisk-menu.git : 62c4321220d4831ceb1812c67fbc9d9e897a1959
license    :
    - GPL-2.0
    - CC-BY-SA-4.0
component  : desktop.mate
summary    : An efficient menu for the MATE Desktop
description: |
    An efficient menu for the MATE Desktop, from the Solus developers.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmate-menu)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
